### ISSUE TITLE
update to bevy 0.12

### ISSUE THREAD

**Issue by Occuros** [BlondeBurrito/bevy_flowfield_tiles_plugin#39]
It seems that the plugin should work with bevy 0.12, the only change needed is to upgrade the used bevy version.

**Comment by BlondeBurrito** [comment]
On it's way :) I was hoping to bundle some extra changes in but I think I'll publish the next crate at bevy 0.12 then do another release later on with some enhancements I've been working on. When I get home from work I'll do a release

**Comment by BlondeBurrito** [comment]
Ah bevy 0.12 breaks most of the examples due to FixedTime changes. I'll sort them out and do a release in a couple hours or so

**Comment by Occuros** [comment]
Ah I didn't test the examples, indeed those might break.

I just tested my project with a local reference.

I think the new fixed timestep can now be done with:

`.add_systems(Update, actor_steering.run_if(on_timer(Duration::from_secs_f32(ACTOR_TIMESTEP))))`

**Comment by BlondeBurrito** [comment]
Just waiting on the pipelines to pass ok then I'll merge, generate the changelog and cargo publish. The jankiness of the custom collision detection in the examples has grown more pronounced but that's separate from what this plugin is about, I've set the systems to use the internal FixedTime clock as that's closer to what they were originally although in truth the physics collision detection and movement should probably be in Fixed while actor steering/direction calc should be in the VirtualTime (which is what you're snippet uses I believe).

Either way I'm going to be adding new/replacing examples showcasing integrating this with rapier and xpbd as they do physics far better than what I can write (and I don't want to get bogged down writing a physics system just for some examples when really I want to spend the time enhancing the algorithm itself haha)
