### ISSUE TITLE
Increasing map size and resolution leads to panic

### ISSUE THREAD

**Issue by Occuros** [BlondeBurrito/bevy_flowfield_tiles_plugin#42]
In the example `3d_actor_movement` if the map size is increased to:

```rust
/// Length`x` of the world
const MAP_LENGTH: u32 = 300;
/// Depth `z` of the world
const MAP_DPETH: u32 = 300;
/// Factor of sectors to create
const SECTOR_RESOLUTION: u32 = 100;
```

And instead of loading the costfield from the .ron file just a simple new map is created without all costs set to the default values:

```rust
cmds.spawn(FlowFieldTilesBundle::new(
MAP_LENGTH,
MAP_DPETH,
SECTOR_RESOLUTION,
ACTOR_SIZE
));
```

The application panics on start with:

```rust
thread 'Compute Task Pool (13)' panicked at 'Cannot get a CostField value, index out of bounds. Asked for column 64, row 34, field column length is 10, field row length is 10', src\flowfields\fields\cost_field.rs:67:13
```

**Comment by BlondeBurrito** [comment]
Ah, thanks for discovering this, it appears I missed a ratio in converting an `(x, y, z)` coord to the `(column, row)` notation. I've just pushed branch `fix/3d_xyz_to_column_row_conversion` which appears to resolve it for those dimensions. I'll add a few more tests before merging it
